runners:
  - name: big-runner
    cloud: digitalocean
    instance_type: c-4
    machine_image: docker-20-04
    region: ams3
    labels:
      - cirun-runner
  - name: azure-runner
    cloud: azure
    instance_type: Standard_F4s_v2
    region:
      - "eastus"
      - "eastus2"
      - "westus3"
    machine_image: "Canonical:0001-com-ubuntu-server-jammy:22_04-lts-gen2:latest"
    labels:
      - cirun-azure-runner