runners:
  - name: big-runner
    cloud: digitalocean
    instance_type: c-4
    machine_image: docker-20-04
    region: ams3
    labels:
      - cirun-runner
  - name: azure-runner
    cloud: azure
    instance_type: F4s_v2
    region: eastus
    machine_image:
      publisher: "Canonical"
      offer: "UbuntuServer"
      sku: "22.04-LTS"
      version: "latest"
    labels:
      - cirun-azure-runner