runners:
  - name: big-runner
    cloud: digitalocean
    instance_type: c-4
    machine_image: docker-20-04
    region: ams3
    labels:
      - cirun-runner
  - name: azure-runner
    cloud: azure
    instance_type: Standard_F4s_v2
    region: eastus2
    machine_image: "Canonical:UbuntuServer:22.04-LTS:latest"
    labels:
      - cirun-azure-runner