name: Docker build ingress-nginx image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    paths:
      - '.github/workflows/docker-build-ingress-nginx.yml'
      - 'ingress-nginx/**'

jobs:

  build:

    runs-on: ${{ (github.event_name == 'workflow_dispatch') && fromJSON('[ "cirun-azure-runner" ]') || 'ubuntu-latest' }}

    steps:
      - name: Get latest tag
        id: get-latest-tag
        run: |
          echo "tag=$(git ls-remote --refs --tags https://github.com/kubernetes/ingress-nginx|grep controller-v|cut --delimiter='/' --fields=3|sort --version-sort|tail --lines=1| awk -F- '{print $NF}')" >> $GITHUB_ENV
        shell: bash

      - uses: actions/cache@v2
        id: cache
        with:
          path: ingress-nginx
          key: ${{ runner.os }}-v3-${{ env.tag }}

      - uses: docker-practice/actions-setup-docker@master
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          platforms: all

      - name: Check Out Repo
        uses: actions/checkout@v3
          
      - name: Check Out Repo kubernetes/ingress-nginx
        uses: actions/checkout@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          repository: "kubernetes/ingress-nginx"
          ref: 'controller-${{ env.tag }}'
          path: 'ingress-nginx-git'

      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Build and push docker base image nginx
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cp ingress-nginx/patches/* ingress-nginx-git
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          cd ingress-nginx-git
          git am *.patch
          docker login quay.io --username ${USERNAME} --password ${DOCKER_TOKEN}
          cd images/nginx
          sudo apt update && sudo apt install build-essential -y
          REGISTRY=quay.io/unixfox TAG=${{ env.tag }} PLATFORMS=linux/amd64,linux/arm64 make push
        env:
          REGISTRY: quay.io/unixfox
          DOCKER_TOKEN: ${{ secrets.QUAY_PASSWORD }}
          USERNAME: ${{ secrets.QUAY_USERNAME }}

      - name: Build and push docker image nginx controller
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          docker login quay.io --username ${USERNAME} --password ${DOCKER_TOKEN}
          cd ingress-nginx-git
          REGISTRY=quay.io/unixfox TAG=${{ env.tag }} BASE_IMAGE=quay.io/unixfox/nginx:${{ env.tag }} PLATFORMS="amd64 arm64" BUILDX_PLATFORMS=linux/amd64,linux/arm64 make release
        env:
          REGISTRY: quay.io/unixfox
          DOCKER_TOKEN: ${{ secrets.QUAY_PASSWORD }}
          USERNAME: ${{ secrets.QUAY_USERNAME }}
